services:
  - type: web
    name: flash-attention-viz
    runtime: static
    rootDir: flash-attention-demo
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
